export const vaccins = [
  {
    nom: 'BBIBP-CorV',
    inventeurs: ['Sinopharm'],
    production: ['Chine'],
    technologie: 'virus inactivé',
    quantité: 420,
    prix: 17,
    approuvé: true,
  }, {
    nom: 'Sputnik V',
    inventeurs: ['Gamaleya'],
    production: ['Russie', 'Inde'],
    technologie: 'adenovirus',
    quantité: 130,
    prix: 12,
    approuvé: false,
  },
  {
    nom: 'AZD1222',
    inventeurs: ['AstraZeneca', 'University of Oxford'],
    production: ['Royaume-Uni', 'Brésil', 'Inde'],
    technologie: 'adenovirus',
    quantité: 5028,
    prix: 1.78,
    approuvé: false,
  }, {
    nom: 'Tozinameran',
    inventeurs: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    production: ['Allemagne', 'USA'],
    technologie: 'ARN messager',
    quantité: 980,
    prix: 14,
    approuvé: true,
  },
  {
    nom: 'mRNA-1273',
    inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    production: ['USA'],
    technologie: 'ARN messager',
    quantité: 240,
    prix: 28,
    approuvé: false,
  },
  {
    nom: 'Ad26.COV2.S',
    inventeurs: ['Johnson & Johnson', 'BIDMC'],
    production: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    technologie: 'adenovirus',
    quantité: 110,
    prix: 31,
    approuvé: false,
  },
];
